name: Publish GHCR Image
on:
  release: 
    types: [published]

  pull_request:
    branches: [main]

jobs:
  build_container:
    name: Build Docker image
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-20.04
    steps:
      - name: Build the image
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: latest
  
  push_to_registry:
    name: Push Docker image to Github Container Registry
    if: github.event_name == 'release'
    runs-on: ubuntu-20.04
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout project
        uses: actions/checkout@v3
      - name: aa
        run: echo ${{ github.actor }}
      - name: Build and push image to GHCR
        uses: docker/build-push-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          tags: latest
